name: habitat_data_collector
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - cmake
  - pip
  - numpy
  - pillow
  - matplotlib
  - pyyaml
  - scipy
  - tqdm
  - pip:
      - opencv-python==4.10.0.84
      - hydra-core
      - omegaconf
